name: Auto Issue (every 5 min)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '2/5 * * * *'

permissions:
  issues: write

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue via API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues \
            -f title="Pulse $(date -u +'%F %T')" \
            -f body="Automated issue from schedule (UTC time above)." \
            -f labels='["automation","pulse"]'
